service: showme

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

plugins:
  - serverless-plugin-typescript

custom:
  typescript:
    # point the TS plugin at your functions-specific config:
    tsConfig: tsconfig.functions.json

functions:
  createMap:
    handler: functions/createMap.handler
    events:
      - http:
          path: maps
          method: post
          cors: true
  getPins:
    handler: functions/getPins.handler
    events:
      - http:
          path: maps/{mapId}/pins
          method: get
          cors: true
  addPin:
    handler: functions/addPin.handler
    events:
      - http:
          path: maps/{mapId}/pins
          method: post
          cors: true
